title: Siddhartha S. Srinivasa
subtitle: Sidd's personal website
author: Siddhartha Srinivasa
simple_search: http://google.com/search
description: Research notes, papers, and robot videos 
baseurl: "/website-tufte" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
name: siddh
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Seattle
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
twitter_username: siddhss5
github_username:  siddhss5

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: clayh53/tufte-jekyll